# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91f58e6247dcc2c489bd897fbdda88d19a95aa9c5e3300747ffe56e066e3b83b1cce1550ca8990da46a62d3f390f40efc784c81a59ec68cccdf0b1fe4d8b2f38

test:
  secret_key_base: bb6dc3183398d7ebe7032d18c9651109844c75a78a213ccf0fbfbd0ed746ce517169c11d1c0d9113015f4d8361056d25abe23b4dbb559cce4f9818add68da887

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
